name: CI/CD for Cloud Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run tests
        run: pytest # Replace with your testing command

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2.304.0
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Cloud Functions
        run: |
          gcloud config set project calcium-sunbeam-341614
          gcloud functions deploy your-function \
            --runtime python309 \
            --trigger-http \
            --allow-unauthenticated \
            --region us-central1 

